return {
	-- "saghen/blink.cmp",
	-- version = "v0.*",
	-- dependencies = { "rafamadriz/friendly-snippets" },
	--
	-- opts = {
	-- 	keymap = { preset = "default" },
	-- 	appearance = {
	-- 		use_nvim_cmp_as_default = false,
	-- 		nerd_font_variant = "mono",
	-- 	},
	--
	-- 	sources = {
	-- 		default = { "snippets", "lsp", "path", "buffer" },
	--
	-- 		providers = {
	-- 			snippets = {
	-- 				opts = {
	-- 					search_paths = { vim.fn.stdpath("config") .. "/snippets" },
	-- 				},
	-- 			},
	-- 		},
	-- 	},
	-- 	signature = { enabled = true },
	-- },
	-- opts_extend = { "sources.default" },
    --
}
